---
title: "Exploratory data analysis"
output: html_document
---

Loading the dataset:
```{r, echo=FALSE}
master_data <- read.csv("master_data.csv")
descriptions <- read.csv("columns_description.csv")
```

Loading packages:
```{r, echo=FALSE}
pacman::p_load(
  ggplot2,
  data.table,
  dplyr,
  cowplot,
  dplyr,
  rlang,
  forcats,
  tidyverse,
  psych)
```

Standardizing:
```{r}
master_data$AMT_INCOME_TOTAL <- (master_data$AMT_INCOME_TOTAL - mean(master_data$AMT_INCOME_TOTAL)) / sd(master_data$AMT_INCOME_TOTAL)
master_data$AMT_CREDIT <- (master_data$AMT_CREDIT - mean(master_data$AMT_CREDIT)) / sd(master_data$AMT_CREDIT)
master_data$AMT_ANNUITY <- (master_data$AMT_ANNUITY - mean(master_data$AMT_ANNUITY)) / sd(master_data$AMT_ANNUITY)
master_data$AMT_GOODS_PRICE <- (master_data$AMT_GOODS_PRICE - mean(master_data$AMT_GOODS_PRICE)) / sd(master_data$AMT_GOODS_PRICE)
```


Plot of target variable:
```{r}


```

#Density plots
```{r}
# Creating the first row
p1 <- ggplot(master_data, aes(x = AGE, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  theme(legend.justification = "top") +
  xlab("Age") +
  ylab("Density") +
  scale_fill_discrete(name = "Payment difficulties") +
  theme(legend.key.size = unit(1, 'cm'))

legend <- get_legend(p1)
p1 <- p1 + theme(legend.position = "none")

p2 <- ggplot(master_data, aes(x = YEARS_REGISTRATION, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  xlab("Years registration") +
  ylab("Density")

p3 <- ggplot(master_data, aes(x = YEARS_PUBLISH, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  xlab("Years publish") +
  ylab("Density")

plots <- align_plots(p1, p2, p3, align = 'v', axis = 'l')

# First row
first_row <- plot_grid(plots[[1]], plots[[2]], plots[[3]], legend,
  labels = c("A", "B", "C"),
  rel_widths = c(1, 1, 1, 0.4),
  nrow = 1)

# Creating the second row
p4 <- ggplot(master_data, aes(x = YEARS_PHONE_CHANGE, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  theme(legend.justification = "top") +
  xlab("Years phone change") +
  ylab("Density")

p5 <- ggplot(master_data, aes(x = REGION_POPULATION_RELATIVE, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  xlab("Relative region population") +
  ylab("Density")

p6 <- ggplot(master_data, aes(x = AMT_INCOME_TOTAL, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 5)) + #obs is changed to 5 to be able to see the density
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  xlab("Total income") +
  ylab("Density")

plots <- align_plots(p4, p5, p6, align = 'v', axis = 'l')

# Second row
second_row <- plot_grid(plots[[1]], plots[[2]], plots[[3]], NULL,
  labels = c("D", "E", "F"),
  rel_widths = c(1, 1, 1, 0.4),
  nrow = 1)

# Creating the third row
p7 <- ggplot(master_data, aes(x = AMT_CREDIT, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  theme(legend.justification = "top") +
  xlab("Credit amount") +
  ylab("Density")

p8 <- ggplot(master_data, aes(x = AMT_ANNUITY, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  xlab("Annuity amount") +
  ylab("Density")

p9 <- ggplot(master_data, aes(x = AMT_GOODS_PRICE, fill = factor(TARGET,labels = c("No", "Yes")))) + 
  geom_density(alpha = .5,show.legend = FALSE) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_half_open(12) +
  xlab("Goods price") +
  ylab("Density")

plots <- align_plots(p7, p8, p9, align = 'v', axis = 'l')

# Third row
third_row <- plot_grid(plots[[1]], plots[[2]], plots[[3]], NULL,
  labels = c("G", "H", "I"),
  rel_widths = c(1, 1, 1, 0.4),
  nrow = 1)

plot_grid(first_row, second_row, third_row, ncol = 1)
```
#Plot of categorical variables (ordinal scaled)
## First row
```{r}
#Plot 1
df_calculated <- master_data %>% count(NAME_HOUSING_TYPE,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(NAME_HOUSING_TYPE) %>%
  mutate(Percent = n/sum(n))

p1 <- ggplot(df_calculated,aes(x = NAME_HOUSING_TYPE, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill') +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 0.1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Housing type") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(legend.justification = "top") +
  scale_fill_discrete(name = "Payment difficulties") +
  theme(legend.key.size = unit(1, 'cm'))

legend <- get_legend(p1)
p1 <- p1 + theme(legend.position = "none")

#Plot 2
master_data$NAME_EDUCATION_TYPE[master_data$NAME_EDUCATION_TYPE == "Secondary / secondary special"] <- "Secondary special"

df_calculated <- master_data %>% count(NAME_EDUCATION_TYPE,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(NAME_EDUCATION_TYPE) %>%
  mutate(Percent = n/sum(n))

p2 <- ggplot(df_calculated,aes(x = NAME_EDUCATION_TYPE, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill',show.legend = FALSE) +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 0.1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Education type") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#Plot 3
df_calculated <- master_data %>% count(NAME_FAMILY_STATUS,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(NAME_FAMILY_STATUS) %>%
  mutate(Percent = n/sum(n))

p3 <- ggplot(df_calculated,aes(x = NAME_FAMILY_STATUS, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill',show.legend = FALSE) +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 0.1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Family status") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

plots <- align_plots(p1, p2, p3, align = 'hv', axis = 'b')

# First row
first_row <- plot_grid(plots[[1]], plots[[2]], plots[[3]], legend,
  labels = c("A", "B", "C"),
  rel_widths = c(1, 1, 1, 0.4),
  nrow = 1)
```

## Second row
```{r}
#Plot 4
df_calculated <- master_data %>% count(REGION_RATING_CLIENT_W_CITY,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(REGION_RATING_CLIENT_W_CITY) %>%
  mutate(Percent = n/sum(n))

p4 <- ggplot(df_calculated,aes(x = REGION_RATING_CLIENT_W_CITY, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill',show.legend = FALSE) +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 0.1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Region rating (1-3)") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(vjust = 0.5, hjust=1))

#Plot 5
df_calculated <- master_data %>% count(NAME_INCOME_TYPE,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(NAME_INCOME_TYPE) %>%
  mutate(Percent = n/sum(n))

p5 <- ggplot(df_calculated,aes(x = NAME_INCOME_TYPE, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill',show.legend = FALSE) +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 0.1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Income type") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

#Plot 6
df_calculated <- master_data %>% count(WEEKDAY_APPR_PROCESS_START,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(WEEKDAY_APPR_PROCESS_START) %>%
  mutate(Percent = n/sum(n))

## Reordering to correct order of weekdays
df_calculated$WEEKDAY_APPR_PROCESS_START <- factor(df_calculated$WEEKDAY_APPR_PROCESS_START, levels = c("MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"))

p6 <- ggplot(df_calculated,aes(x = WEEKDAY_APPR_PROCESS_START, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill',show.legend = FALSE) +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 0.1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Weekday application start") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

plots <- align_plots(p4, p5, p6, align = 'hv', axis = 'b')

# Second row
second_row <- plot_grid(plots[[1]], plots[[2]], plots[[3]], NULL,
  labels = c("D", "E", "F"),
  rel_widths = c(1, 1, 1, 0.4),
  nrow = 1)
```

#Collecting all rows into one plot
```{r}
plot_grid(first_row, second_row, ncol = 1)
```
## Second plot of ordinal scaled variables
```{r}
#Plot 1
df_calculated <- master_data %>% count(OCCUPATION_TYPE,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(OCCUPATION_TYPE) %>%
  mutate(Percent = n/sum(n))

p1 <- ggplot(df_calculated,aes(x = OCCUPATION_TYPE, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill') +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 0.1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Occupation type") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(legend.justification = "top") +
  scale_fill_discrete(name = "Payment difficulties") +
  theme(legend.key.size = unit(1, 'cm'))

legend <- get_legend(p1)
p1 <- p1 + theme(legend.position = "none")

#Plot 2
df_calculated <- master_data %>% count(ORGANIZATION_TYPE,TARGET) %>% 
  mutate(Percent_col = n / sum(n)) %>%
  group_by(TARGET) %>%
  group_by(ORGANIZATION_TYPE) %>%
  mutate(Percent = n/sum(n))

p2 <- ggplot(df_calculated,aes(x = ORGANIZATION_TYPE, y = Percent_col, fill = factor(TARGET,labels = c("No", "Yes")))) +
  geom_col(position = 'fill',show.legend = FALSE) +
  scale_y_continuous(labels=scales::percent) +
  geom_text(aes(label = scales::percent(Percent, accuracy = 1)), position = position_fill(vjust = 0.5), size = 3, color = "white") +
  theme_half_open(12) +
  ggtitle("Organisation type") +
  ylab("Percentage") +
  xlab("") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# First row
first_row <- plot_grid(p1, legend,
  labels = c("A"),
  rel_widths = c(2.3, 0.4),
  nrow = 1)

# Second row
second_row <- plot_grid(p2, NULL,
  labels = c("B"),
  rel_widths = c(2.3, 0.4),
  nrow = 1)

#Collecting all rows into one plot
plot_grid(first_row, second_row, ncol = 1)
```



